[InstrumentType] 
    [InstrumentType.C1]
    length = 41 
    instrument_packet_start = 10 
    instrument_packet_length = 10
    [InstrumentType.W2]
    length = 62 
    instrument_packet_start = 10 
    instrument_packet_length = 32 

[ReceiverPacket]
    [ReceiverPacket.packet_version]
    start_index=0
    end_index=1
    output_type="str"
    [ReceiverPacket.timestamp]
    start_index=2
    end_index=5
    output_type="bytes"
    [ReceiverPacket.logger_temp]
    start_index=6
    end_index=9
    output_type="float"
    [ReceiverPacket.logger_pressure]
    start_index=10
    end_index=13
    output_type="float"
    [ReceiverPacket.logger_voltage]
    start_index=14
    end_index=15
    output_type="int"
    [ReceiverPacket.channel_number]
    start_index=16
    end_index=16
    output_type="int"
    [ReceiverPacket.length_byte]
    start_index=17
    end_index=17
    output_type="int"
    [ReceiverPacket.c_field]
    start_index=18
    end_index=18
    output_type="int"
    [ReceiverPacket.manufacturer_id]
    start_index=19
    end_index=20
    output_type="int"
    [ReceiverPacket.user_id]
    start_index=21
    end_index=24
    output_type="int"
    [ReceiverPacket.version_number]
    start_index=25
    end_index=25
    output_type="int"
    [ReceiverPacket.dev]
    start_index=26
    end_index=26
    output_type="int"
    [ReceiverPacket.ci_field]
    start_index=27
    end_index=27
    output_type="int"
    [ReceiverPacket.rssi]
    output_type="int"

[CryoeggPacket]
    [CryoeggPacket.conductivity]
        start_index = 0
        end_index = 1
        output_type = "float"
    [CryoeggPacket.temperature_pt1000]
        start_index = 2
        end_index = 3
        output_type = "float"
    [CryoeggPacket.pressure]
        start_index = 4
        end_index = 5
        output_type = "int"
        parser = "parse_pressure_keller" 
    [CryoeggPacket.temperature]
        start_index = 6
        end_index = 7
        output_type = "int"
    [CryoeggPacket.battery_voltage]
        start_index = 8
        end_index = 9
        output_type = "float"
    [CryoeggPacket.sequence_number]
        start_index = 10
        end_index = 10
        output_type = "int"


[CryowurstPacket]
    [CryowurstPacket.temperature]
        start_index = 0 
        end_index=1
        output_type="float"
    [CryowurstPacket.magnetometer_x]
        start_index = 2
        end_index=3
        output_type="float"
    [CryowurstPacket.magnetometer_y]
        start_index = 4
        end_index= 5
        output_type = "float"
    [CryowurstPacket.magnetometer_z]
        start_index = 6
        end_index= 7
        output_type = "float"
    [CryowurstPacket.accelerometer_x]
        start_index = 14
        end_index= 15
        output_type = "float"
    [CryowurstPacket.accelerometer_y]
        start_index = 16
        end_index= 17
        output_type = "float"
    [CryowurstPacket.accelerometer_z]
        start_index = 18
        end_index= 19
        output_type = "float"
        parser = "parse_accelerometer_z"
    [CryowurstPacket.tilt_x]
        start_index = 20 
        end_index= 21
        output_type = "float"
    [CryowurstPacket.tilt_y]
        start_index = 22 
        end_index= 23
        output_type = "float"
    [CryowurstPacket.tilt_z]
        start_index = 24 
        end_index= 25
        output_type = "float"
        parser = "parse_accelerometer_z"
    [CryowurstPacket.pitch_x]
        start_index =  26
        end_index= 27 
        output_type = "float"
    [CryowurstPacket.roll_y]
        start_index =  28
        end_index= 29
        output_type = "float"
    [CryowurstPacket.conductivity]
        start_index =  30
        end_index= 31
        output_type = "float"
    [CryowurstPacket.pressure]
        start_index = 32 
        end_index= 33
        output_type = "float"
    [CryowurstPacket.keller_temperature]
        start_index =  34
        end_index= 35
        output_type = "float"
    [CryowurstPacket.battery_voltage]
        start_index =  36
        end_index= 37 
        output_type = "float"
    [CryowurstPacket.sequence_number]
        start_index =  38
        end_index= 39
        output_type = "int"
