[InstrumentType] 
    [InstrumentType.C1]
    length =  39
    instrument_packet_start = 18
    instrument_packet_length = 21 
    [InstrumentType.W2]
    length = 62 
    instrument_packet_start = 18
    instrument_packet_length = 46

[ReceiverPacket]
    [ReceiverPacket.timestamp]
    start_index=0
    end_index=3
    output_type="bytes"
    [ReceiverPacket.logger_temp]
    start_index=4
    end_index=7
    output_type="float"
    [ReceiverPacket.logger_pressure]
    start_index=8
    end_index=11
    output_type="float"
    [ReceiverPacket.logger_voltage]
    start_index=12
    end_index=13
    output_type="int"
    [ReceiverPacket.channel_number]
    start_index=14
    end_index=14
    output_type="int"

[CryoeggPacket]
    [CryoeggPacket.c_field]
        start_index = 0
        end_index = 0
    [CryoeggPacket.manufacturer_id]
        start_index = 1 
        end_index = 2
    [CryoeggPacket.user_id]
        start_index = 3
        end_index = 7
    [CryoeggPacket.version_number]
        start_index = 8
        end_index = 8
    [CryoeggPacket.device_id]
        start_index = 9 
        end_index = 9
    [CryoeggPacket.ci_field]
        start_index = 10 
        end_index = 10
    [CryoeggPacket.conductivity]
        start_index = 11
        end_index = 12
        output_type = "float"
    [CryoeggPacket.temperature_pt1000]
        start_index = 13 
        end_index = 14
        output_type = "float"
    [CryoeggPacket.pressure]
        start_index = 15
        end_index = 16
        output_type = "int"
        parser = "parse_pressure_keller" 
    [CryoeggPacket.temperature]
        start_index = 17
        end_index = 18
        output_type = "int"
    [CryoeggPacket.battery_voltage]
        start_index = 19
        end_index = 20
        output_type = "float"
    [CryoeggPacket.sequence_number]
        start_index = 21
        end_index = 21
        output_type = "int"
    [CryoeggPacket.rssi]
        start_index =  22
        end_index = 22
        output_type = "float"


[CryowurstPacket]
    [CryowurstPacket.c_field]
        start_index = 0
        end_index = 0
    [CryowurstPacket.manufacturer_id]
        start_index = 1 
        end_index = 2
    [CryowurstPacket.user_id]
        start_index = 3
        end_index = 7
    [CryowurstPacket.version_number]
        start_index = 8
        end_index = 8
    [CryowurstPacket.device_id]
        start_index = 9 
        end_index = 9
    [CryowurstPacket.ci_field]
        start_index = 10 
        end_index = 10
    [CryowurstPacket.temperature]
        start_index = 11
        end_index=12
        output_type="float"
    [CryowurstPacket.magnetometer_x]
        start_index = 13
        end_index=14
        output_type="float"
    [CryowurstPacket.magnetometer_y]
        start_index = 15
        end_index= 16
        output_type = "float"
    [CryowurstPacket.magnetometer_z]
        start_index = 17
        end_index= 18
        output_type = "float"
    [CryowurstPacket.accelerometer_x]
        start_index = 19
        end_index= 20
        output_type = "float"
    [CryowurstPacket.accelerometer_y]
        start_index = 21
        end_index= 22
        output_type = "float"
    [CryowurstPacket.accelerometer_z]
        start_index = 23
        end_index= 24
        output_type = "float"
        parser = "parse_accelerometer_z"
    [CryowurstPacket.tilt_x]
        start_index = 25 
        end_index= 26
        output_type = "float"
    [CryowurstPacket.tilt_y]
        start_index =  27
        end_index= 28
        output_type = "float"
    [CryowurstPacket.tilt_z]
        start_index =  29
        end_index= 30
        output_type = "float"
        parser = "parse_accelerometer_z"
    [CryowurstPacket.pitch_x]
        start_index =  31
        end_index= 32 
        output_type = "float"
    [CryowurstPacket.roll_y]
        start_index =  33
        end_index= 34
        output_type = "float"
    [CryowurstPacket.conductivity]
        start_index =  35
        end_index= 36
        output_type = "float"
    [CryowurstPacket.pressure]
        start_index =  37
        end_index= 38
        output_type = "float"
    [CryowurstPacket.keller_temperature]
        start_index =  39
        end_index= 40
        output_type = "float"
    [CryowurstPacket.battery_voltage]
        start_index =  41
        end_index=  42
        output_type = "float"
    [CryowurstPacket.sequence_number]
        start_index =  43
        end_index= 44
        output_type = "int"
    [CryowurstPacket.rssi]
        start_index =  45
        end_index=  46
        output_type = "float"
