[InstrumentType] 
    [InstrumentType.C1]
    length =  39
    instrument_packet_start = 18
    instrument_packet_length = 21 
    [InstrumentType.W2]
    length = 62 
    instrument_packet_start = 18
    instrument_packet_length = 46

[ReceiverPacket]
    [ReceiverPacket.timestamp]
    start_index=0
    end_index=3
    output_type="bytes"
    [ReceiverPacket.logger_temp]
    start_index=4
    end_index=7
    output_type="float"
    [ReceiverPacket.logger_pressure]
    start_index=8
    end_index=11
    output_type="float"
    [ReceiverPacket.logger_voltage]
    start_index=12
    end_index=13
    output_type="int"
    [ReceiverPacket.channel_number]
    start_index=14
    end_index=14
    output_type="int"

[CryoeggPacket]
    [CryoeggPacket.c_field]
        start_index = 0
        end_index = 0
    [CryoeggPacket.manufacturer_id]
        start_index = 1 
        end_index = 2
    [CryoeggPacket.user_id]
        start_index = 3
        end_index =6 
    [CryoeggPacket.version_number]
        start_index = 7 
        end_index = 7
    [CryoeggPacket.device_id]
        start_index = 8 
        end_index = 8
    [CryoeggPacket.ci_field]
        start_index = 9 
        end_index = 9 
    [CryoeggPacket.conductivity]
        start_index = 10 
        end_index = 11
        output_type = "float"
    [CryoeggPacket.temperature_pt1000]
        start_index =  12
        end_index = 13
        output_type = "float"
    [CryoeggPacket.pressure]
        start_index = 14
        end_index = 15
        output_type = "int"
        parser = "parse_pressure_keller" 
    [CryoeggPacket.temperature]
        start_index = 16
        end_index = 17
        output_type = "int"
    [CryoeggPacket.battery_voltage]
        start_index = 18
        end_index = 19
        output_type = "float"
    [CryoeggPacket.sequence_number]
        start_index = 20
        end_index = 20
        output_type = "int"
    [CryoeggPacket.rssi]
        start_index =  21
        end_index = 21
        output_type = "float"


[CryowurstPacket]
    [CryowurstPacket.c_field]
        start_index = 0
        end_index = 0
    [CryowurstPacket.manufacturer_id]
        start_index = 1 
        end_index = 2
    [CryowurstPacket.user_id]
        start_index = 3
        end_index = 6 
    [CryowurstPacket.version_number]
        start_index = 7
        end_index = 7
    [CryowurstPacket.device_id]
        start_index = 8
        end_index = 8
    [CryowurstPacket.ci_field]
        start_index = 9
        end_index = 9
    [CryowurstPacket.temperature]
        start_index = 10
        end_index=11
        output_type="float"
    [CryowurstPacket.magnetometer_x]
        start_index = 12
        end_index=13
        output_type="float"
    [CryowurstPacket.magnetometer_y]
        start_index = 14
        end_index= 15
        output_type = "float"
    [CryowurstPacket.magnetometer_z]
        start_index = 16
        end_index= 17
        output_type = "float"
    [CryowurstPacket.accelerometer_x]
        start_index = 18
        end_index= 19
        output_type = "float"
    [CryowurstPacket.accelerometer_y]
        start_index = 20
        end_index= 21
        output_type = "float"
    [CryowurstPacket.accelerometer_z]
        start_index = 22
        end_index= 23
        output_type = "float"
        parser = "parse_accelerometer_z"
    [CryowurstPacket.tilt_x]
        start_index = 24
        end_index= 25
        output_type = "float"
    [CryowurstPacket.tilt_y]
        start_index =  26
        end_index= 27
        output_type = "float"
    [CryowurstPacket.tilt_z]
        start_index =  28
        end_index= 29
        output_type = "float"
        parser = "parse_accelerometer_z"
    [CryowurstPacket.pitch_x]
        start_index =  30
        end_index= 31
        output_type = "float"
    [CryowurstPacket.roll_y]
        start_index =  32
        end_index= 33
        output_type = "float"
    [CryowurstPacket.conductivity]
        start_index =  34
        end_index= 35
        output_type = "float"
    [CryowurstPacket.pressure]
        start_index =  36
        end_index= 37
        output_type = "float"
    [CryowurstPacket.keller_temperature]
        start_index =  38
        end_index= 39
        output_type = "float"
    [CryowurstPacket.battery_voltage]
        start_index =  40
        end_index=  41
        output_type = "float"
    [CryowurstPacket.sequence_number]
        start_index =  42
        end_index= 42
        output_type = "int"
    [CryowurstPacket.rssi]
        start_index =  43
        end_index=  43
        output_type = "float"
